### ISSUE TITLE
Publish release

### ISSUE THREAD

**Issue by hello-smile6** [Brick-OS-PokeyManatee4/brick-os-beta-bios#1]
It'd be nice to have a prebuilt disk image to use.

**Comment by PokeyManatee4** [comment]
Well I Have Not Fully Made It Yet Tho
@hello-smile6

**Comment by PokeyManatee4** [comment]
Also Just Get It From The Actions Tab

**Comment by hello-smile6** [comment]
> Also Just Get It From The Actions Tab

Want me to add an action that'll auto-publish your image?

**Comment by hello-smile6** [comment]
I mean, as a release.

**Comment by PokeyManatee4** [comment]
> > Also Just Get It From The Actions Tab
> 
> Want me to add an action that'll auto-publish your image?

Sure Plus I Will Add You To My ORG

**Comment by PokeyManatee4** [comment]
Well Ok But Im Doing The Rest Add Me On Gitter
