### ISSUE TITLE
.flp

### ISSUE THREAD

**Issue by BoogieHasFun** [Brick-OS-PokeyManatee4/brick-os-beta-bios#7]
.flp is a fl studio project file, i think it shouldn't a fl studio project

**Comment by PokeyManatee4** [comment]
No its also a floppy

**Comment by PokeyManatee4** [comment]
I cant use the .bin file extension

**Comment by PokeyManatee4** [comment]
v86 failed to understand if its a floppy or a binary

**Comment by PokeyManatee4** [comment]
<div class="entryHeader" style="box-sizing: border-box; display: grid; grid-template-columns: 80px auto; place-items: center start; padding: 40px 0px 0px; position: relative; color: rgb(10, 10, 10); font-family: system-ui, -apple-system, BlinkMacSystemFont, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2 class="title" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 15px; grid-area: 1 / 1 / span 1 / span 2; font-size: 1.25em; font-weight: 700;"><br class="Apple-interchange-newline">Floppy Disk Image</h2>

Developer | N/A
-- | --
Popularity |  
Category | Disk Image Files
Format | Binary

</div><h2 id="floppy_disk_image_info" class="heading" style="box-sizing: border-box; padding: 0px; margin: 15px 0px; font-size: 1em; font-weight: 700; color: rgb(10, 10, 10); font-family: system-ui, -apple-system, BlinkMacSystemFont, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">What is an FLP file?</h2><div class="infoBox" style="box-sizing: border-box; color: rgb(10, 10, 10); font-family: system-ui, -apple-system, BlinkMacSystemFont, Roboto, Oxygen-Sans, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; padding: 0px; margin: 0px; line-height: 1.6;">An FLP file is a disk image created from a 3.5"<span> </span><a href="https://techterms.com/definition/floppydisk" target="_blank" style="box-sizing: border-box; text-decoration: none; color: var(--linkcolor); font-weight: 600;">floppy disk</a>. Users often create FLP files using an MS-DOS program or a program from an older version of Windows. The files can be used for storing bootable files and booting up guest operating systems on virtualized platforms. They may also be used for copying the contents of a disk to multiple diskettes</p></div>Floppy Disk Image
Developer	N/A
Popularity	
Category	[Disk Image Files](https://fileinfo.com/filetypes/disk_image)
Format	Binary
What is an FLP file?
An FLP file is a disk image created from a 3.5" [floppy disk](https://techterms.com/definition/floppydisk). Users often create FLP files using an MS-DOS program or a program from an older version of Windows. The files can be used for storing bootable files and booting up guest operating systems on virtualized platforms. They may also be used for copying the contents of a disk to multiple diskettes

**Comment by PokeyManatee4** [comment]
In our case we are using it to boot brick os

**Comment by PokeyManatee4** [comment]
Also prs are accepted

**Comment by PokeyManatee4** [comment]
Its also a document so thx I guess

**Comment by BoogieHasFun** [comment]
well it thinks its a fl studio project, though how the fuck do i boot this off a virtual machine

**Comment by PokeyManatee4** [comment]
bochs

**Comment by hello-smile6** [comment]
@BoogieHasFun F*** bochs, use qemu. Bochs is s**t. Uploading an x64 binary to a new Github release.

**Comment by PokeyManatee4** [comment]
Tried Qemu it dont work @hello-smile6

**Comment by PokeyManatee4** [comment]
Still Dont
