### ISSUE TITLE
website shows no os

### ISSUE THREAD

**Issue by BoogieHasFun** [Brick-OS-PokeyManatee4/brick-os-beta-bios#8]
is this normal or is it broken?

**Comment by PokeyManatee4** [comment]
Its A V86 Issue We Do believe

**Comment by PokeyManatee4** [comment]
for right now just use bochs it dont work in any else rn

**Comment by PokeyManatee4** [comment]
Ask @hello-smile6 bout that one he is the javascript expert not me

**Comment by hello-smile6** [comment]
Our current build is broken, I'll push an update as soon as possible. Let me get my Debian VM up and import my SSH keys.
